# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@6.1.0

jobs:
  test:
    docker:
      - image: cimg/node:22.9.0-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install --save
      #- run:
      #    name: Upgrade NPM
      #    command: 'npm install -g npm@latest && npm i -g npm-upgrade'
      - run:
          name: Install dependencies and audit them
          command: npm audit fix || true
          environment:
            CI: "false"
      - run:
          name: Run Tests
          command: 'npm test || true'

workflows:
  version: 2
  test:
    jobs:
      - test