# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies and audit them
          command: CI=false && npm i --save && npm audit fix
      - run:
          name: Run Tests
          command: CI=false && npm test || true

workflows:
  version: 2
  test:
    jobs:
      - test